version: '3.8'

services:

  myappbun:
    image: 'myappbun'
    env_file:
      - ./.env
    working_dir: /home/bun/app
    volumes:
      - ./:/home/bun/app
    command: sh -c "bun run ./source/database/database.create-databases.ts && bun start"
    ports:
      - 3000:3000